version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: thanosql-ai-chat-fe-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3800:5173'
    environment:
      - NODE_ENV=development
    command: ['yarn', 'dev']
