version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thanosql-ai-chat-fe
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=production
